version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  web:
    build: ./web
    restart: always
    container_name: web
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
